services:
  - type: static
    name: mi-proyecto01
    buildCommand: npm install && npm run build
    staticPublishPath: dist/mi-proyecto01/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
