services:
  - type: web
    name: mi-proyecto01
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist/mi-proyecto01/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
